name: Maven Package and Docker Build

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v3

      # 2. 缓存 Maven 包以加快构建速度
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 3. 设置 JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}/.github

      # 4. 登录到 Docker 注册表（以 Docker Hub 为例）
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. 构建并发布 Maven 包到 GitHub Packages
      - name: Build with Maven
        run: mvn -B -X package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -X deploy -s ${{ github.workspace }}/.github/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # 6. 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ymyyh/aliyun-deemo:latest